## Parte I: Cargar y observar como esta distribuido el dataset

In [34]:
# Loading data
# ------------

import pandas as pd

df =  pd.read_csv('../data/most_used_beauty_cosmetics_products_extended.csv')
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany

In [35]:
# Basic inspection
# ----------------
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_Name       15000 non-null  object
 1   Brand              15000 non-null  object
 2   Category           15000 non-null  object
 3   Usage_Frequency    15000 non-null  object
 4   Price_USD          15000 non-null  float64
 5   Rating             15000 non-null  float64
 6   Number_of_Reviews  15000 non-null  int64
 7   Product_Size       15000 non-null  object
 8   Skin_Type          15000 non-null  object
 9   Gender_Target      15000 non-null  object
 10  Packaging_Type     15000 non-null  object
 11  Main_Ingredient    15000 non-null  object
 12  Cruelty_Free       15000 non-null  bool
 13  Country_of_Origin  15000 non-null  object
dtypes: bool(1), float64(2), int64(1), object(10)
memory usage: 1.5+ MB

- El total de las filas existentes son 15000 y estan enumeradas de 0 a 14999
- El total de columnas son 14
- No hay datos faltantes en las diferentes columnas (15000 non-null)
- Hay 15000 productos en total
- Los datos existentes para cada columna son:
    - 0   Product_Name -> String
    - 1   Brand        -> String 
    - 2   Category     -> String  
    - 3   Usage_Frequency -> String 
    - 4   Price_USD    -> float
    - 5   Rating       -> float
    - 6   Number_of_Reviews ->  int
    - 7   Product_Size  -> String
    - 8   Skin_Type     -> String
    - 9   Gender_Target -> String
    - 10  Packaging_Type -> String
    - 11  Main_Ingredient  -> String
    - 12  Cruelty_Free  ->  bool   
    - 13  Country_of_Origin  -> String

In [36]:
# Descriptive statistics
df.describe()

          Price_USD        Rating  Number_of_Reviews
count  15000.000000  15000.000000       15000.000000
mean      80.134108      3.002327        5014.231333
std       40.402983      1.168029        2855.665464
min       10.000000      1.000000          52.000000
25%       45.480000      2.000000        2562.000000
50%       80.040000      3.000000        5002.000000
75%      114.760000      4.000000        7497.000000
max      149.990000      5.000000       10000.000000

- **Price_USD:**
    - **Promedio:** 80.13 USD, Los productos posee en promedio un precio de 80.13 USD
    - **Rango:** De 10 USD a 114.76 USD, hay productos con el precio de 10 y productos mas costoso de 149.99
    - **Desviación Estandar:** 40.40 USD respecto al promedio, sugiere que es una variablidad media a alta, ya que la desviacion estandar representa el 50.41 % del promedio, sugiriendo que hay productos cuya variabilidad de precios esta alejado del promedio, duplicando incluso el valor del precio promedio.
    - **Quartiles:**
        - El 25% de los productos cuesta 45.48 USD o menos, lo que quiere decir que los productos mas economico esta por debajo de este precio
        - El 50% de los productos posee un precio de 80.04 USD, este hace referencia a la mediana, indicando que la mitad de los precios de los productos esta por debajo DE 80.04 USD y la otra por encima
        - El 75% de los productos posee un precio de 114.76 USD o menos, mostrando que el 75% de los productos tiene un precio menor de este y otro 25% de productos tiene un precio superior a 114.76 USD


- **Rating:**
    - **Promedio:** 3, Los productos poseen en promedio un rating de 3 puntos
    - **Rango:**: De 1 a 5, hay productos con 1 punto y otros con muy buenos puntos (hasta 5).
    - **Desviación Estandar:** 1.16 respecto al promedio, significa que los valores de rating varian 1.16 con respecto al valor del promedio 3, aunque representa el 38%, considero que la variabilidad es moderada ya que se trata de rating, pienso que la mayoria de los valores estan cerca de la media pero aun asi existe algo de variabilidad o dispersión.
    - **Quartiles:**
        - El 25% de los productos cosmeticos posee una puntuacion menor o igual a 2
        - El 50% de los productos posee una puntuacion mediana de 3, mostrando que la mitad de los productos posee un puntuacion por encima de 3 y otra por debajo.
        - El 75% de los productos posee una puntiacion menor o igual 4 y el otro 25 restante superior a 4.

- **Number_of_Reviews:**
    - **Promedio:** 5014.23, Los productos poseen en promedio alrededor de 5000 reseñas.
    - **Rango:** De 52 a 10000, Hay productos con pocas reseñas(52) y otros con muchas reseñas (hasta 10.000).
    - **Desviación Estandar:** 2855.66 respecto al promedio, podria decirse que es una variabilidad media a alta, ya que representa el 57 % del promedio, esto sugiere que hay productos tanto con pocas como con muchas reseñas, reflejando diversidad en la cantidad de reseñas recibidas.
    - **Quartiles:**
        - El 25% de los productos posee un total de reviews menor o igual a 2562
        - El 50% La mediana delos productos es de 5002 review mostrando que el 50% los productos tienen menos de 5002 reviews y el 50% restante tiene mas de 5002.
        - El 75% de los productos posee reviews con un total de 7497 reviews o menos, mientras que el 25% por encima de 7497

## Parte II: Preprocesamiento

In [37]:
# Verify values null
df.isnull().sum()

Product_Name         0
Brand                0
Category             0
Usage_Frequency      0
Price_USD            0
Rating               0
Number_of_Reviews    0
Product_Size         0
Skin_Type            0
Gender_Target        0
Packaging_Type       0
Main_Ingredient      0
Cruelty_Free         0
Country_of_Origin    0
dtype: int64

El total de las sumas para los valores nulos da 0, confirmando que no existen columnas con valores nulos

In [38]:
# Revition types of data
df.dtypes

Product_Name          object
Brand                 object
Category              object
Usage_Frequency       object
Price_USD            float64
Rating               float64
Number_of_Reviews      int64
Product_Size          object
Skin_Type             object
Gender_Target         object
Packaging_Type        object
Main_Ingredient       object
Cruelty_Free            bool
Country_of_Origin     object
dtype: object

In [39]:
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany

In [40]:
# Verify duplicate values for registers
duplicates = df.duplicated().sum()
print(f"Registros duplicados encontrados: {duplicates}")

Registros duplicados encontrados: 0

### Verificar valores únicos en columnas categóricas

In [41]:
# Identify category 
columnas_categoricas = ['Product_Name', 'Brand', 'Category', 'Usage_Frequency', 
                        'Product_Size', 'Skin_Type', 'Gender_Target', 
                        'Packaging_Type', 'Main_Ingredient', 'Country_of_Origin']
columnas_categoricas

['Product_Name',
 'Brand',
 'Category',
 'Usage_Frequency',
 'Product_Size',
 'Skin_Type',
 'Gender_Target',
 'Packaging_Type',
 'Main_Ingredient',
 'Country_of_Origin']

In [42]:
# Verify quantity of values unique for category
resumen_categorias = pd.DataFrame({
    'columna': columnas_categoricas,
    'Valores Unicos':[df[col].nunique() for col in columnas_categoricas]
})
print(resumen_categorias)

             columna  Valores Unicos
0       Product_Name             120
1              Brand              40
2           Category              24
3    Usage_Frequency               4
4       Product_Size               6
5          Skin_Type               5
6      Gender_Target               3
7     Packaging_Type               6
8    Main_Ingredient               7
9  Country_of_Origin               8

Se podria indicar que la cantidad de valores unicos que presentan las columnas son numeros razonables con respecto al contexto de cada una, por ejemplo:

- **Product_Name(120)**: Cantidad variada con respecto a la cantidad de productos.
- **Brand(40)**: El rubro posee muchas marcas diferentes.
- **Usage_Frequency(4) y Gender_Target(3):** Pocas opciones, como se esperaría en datos categóricos estandarizados.

In [43]:
# Observ what is the quantity of time that apperar each value unique
for col in columnas_categoricas:
    print(f"Dist. Columna '{col}':")
    print(df[col].value_counts())
    print('-' * 50)

Dist. Columna 'Product_Name':
Product_Name
Super Setting Spray     154
Magic Face Oil          151
Magic Lip Liner         149
Perfect Lip Liner       147
Divine Exfoliator       146
                       ...
Ultra Makeup Remover    103
Super Bronzer           102
Ultra Primer            101
Magic Exfoliator         96
Magic Moisturizer        93
Name: count, Length: 120, dtype: int64
--------------------------------------------------
Dist. Columna 'Brand':
Brand
Milk Makeup                426
Make Up For Ever           414
Kiehl’s                    411
NARS                       400
E.l.f.                     399
Farsali                    399
Yves Saint Laurent         394
Sisley                     392
Bite Beauty                392
Morphe                     392
KVD Beauty                 391
Becca                      388
Glossier                   388
Huda Beauty                384
RMS Beauty                 382
Bobby Brown                380
Ilia Beauty                379
Clinique                   377
Rare Beauty                375
Tatcha                     374
Too Faced                  371
Kylie Cosmetics            370
Shiseido                   370
Anastasia Beverly Hills    369
Drunk Elephant             368
Juvia’s Place              368
Fenty Beauty               366
Hourglass                  366
Natasha Denona             366
Charlotte Tilbury          364
Tarte                      361
Danessa Myricks            358
Bourjois                   357
Urban Decay                356
Laura Mercier              355
Perricone MD               349
IT Cosmetics               346
Patrick Ta                 345
Pat McGrath Labs           330
ColourPop                  328
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Category':
Category
Serum             710
Mascara           674
Face Oil          671
Face Mask         653
Highlighter       653
Moisturizer       638
Makeup Remover    636
Concealer         633
Lipstick          633
Bronzer           631
Eyeliner          629
Blush             628
Setting Spray     622
Cleanser          614
BB Cream          613
Foundation        613
Lip Liner         610
Primer            606
Contour           604
Powder            599
CC Cream          594
Exfoliator        583
Eye Shadow        582
Lip Gloss         571
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Usage_Frequency':
Usage_Frequency
Occasional    3794
Monthly       3781
Weekly        3757
Daily         3668
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Product_Size':
Product_Size
100ml    2551
30ml     2540
50ml     2501
250ml    2498
150ml    2487
200ml    2423
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Skin_Type':
Skin_Type
Combination    3060
Oily           3009
Normal         2991
Sensitive      2975
Dry            2965
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Gender_Target':
Gender_Target
Male      5017
Female    5002
Unisex    4981
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Packaging_Type':
Packaging_Type
Jar        2567
Bottle     2532
Stick      2529
Spray      2528
Compact    2454
Tube       2390
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Main_Ingredient':
Main_Ingredient
Retinol            2180
Glycerin           2174
Vitamin C          2168
Salicylic Acid     2149
Shea Butter        2148
Aloe Vera          2091
Hyaluronic Acid    2090
Name: count, dtype: int64
--------------------------------------------------
Dist. Columna 'Country_of_Origin':
Country_of_Origin
Italy          1942
USA            1931
Australia      1873
France         1863
Japan          1861
South Korea    1851
UK             1846
Germany        1833
Name: count, dtype: int64
--------------------------------------------------

Observar la distribucion de cada categoria ordenada alfabeticamente y asi diferenciar de una manera simple

In [44]:
df["Brand"].value_counts().sort_index()

Brand
Anastasia Beverly Hills    369
Becca                      388
Bite Beauty                392
Bobby Brown                380
Bourjois                   357
Charlotte Tilbury          364
Clinique                   377
ColourPop                  328
Danessa Myricks            358
Drunk Elephant             368
E.l.f.                     399
Farsali                    399
Fenty Beauty               366
Glossier                   388
Hourglass                  366
Huda Beauty                384
IT Cosmetics               346
Ilia Beauty                379
Juvia’s Place              368
KVD Beauty                 391
Kiehl’s                    411
Kylie Cosmetics            370
Laura Mercier              355
Make Up For Ever           414
Milk Makeup                426
Morphe                     392
NARS                       400
Natasha Denona             366
Pat McGrath Labs           330
Patrick Ta                 345
Perricone MD               349
RMS Beauty                 382
Rare Beauty                375
Shiseido                   370
Sisley                     392
Tarte                      361
Tatcha                     374
Too Faced                  371
Urban Decay                356
Yves Saint Laurent         394
Name: count, dtype: int64

In [45]:
df["Category"].value_counts().sort_index()

Category
BB Cream          613
Blush             628
Bronzer           631
CC Cream          594
Cleanser          614
Concealer         633
Contour           604
Exfoliator        583
Eye Shadow        582
Eyeliner          629
Face Mask         653
Face Oil          671
Foundation        613
Highlighter       653
Lip Gloss         571
Lip Liner         610
Lipstick          633
Makeup Remover    636
Mascara           674
Moisturizer       638
Powder            599
Primer            606
Serum             710
Setting Spray     622
Name: count, dtype: int64

In [46]:
df["Usage_Frequency"].value_counts().sort_index()

Usage_Frequency
Daily         3668
Monthly       3781
Occasional    3794
Weekly        3757
Name: count, dtype: int64

In [47]:
df["Skin_Type"].value_counts().sort_index()

Skin_Type
Combination    3060
Dry            2965
Normal         2991
Oily           3009
Sensitive      2975
Name: count, dtype: int64

In [48]:
df["Gender_Target"].value_counts().sort_index()

Gender_Target
Female    5002
Male      5017
Unisex    4981
Name: count, dtype: int64

In [49]:
df["Packaging_Type"].value_counts().sort_index()

Packaging_Type
Bottle     2532
Compact    2454
Jar        2567
Spray      2528
Stick      2529
Tube       2390
Name: count, dtype: int64

In [50]:
df["Main_Ingredient"].value_counts().sort_index()

Main_Ingredient
Aloe Vera          2091
Glycerin           2174
Hyaluronic Acid    2090
Retinol            2180
Salicylic Acid     2149
Shea Butter        2148
Vitamin C          2168
Name: count, dtype: int64

En ninguna de las columnas categoricas observe valores mal escritos y por ello duplicados ni inconsistencia con respecto al total de columnas

**Entonces en las columnas categoricas se conculye que:**
- Los datos esta bien escritos y estructurados.
- No hay duplicados ni inconsistencias visisbles.

#### Transformacion de columnas categoricas

##### *Clasificacion columnas categoricas*

- **Ordinales (jerarquía o clasificacion que implica magnitud o progesion):**
    1. Category: Posee una relacion funcional a traves de una secuencia de uso: Makeup Remover → Foundation → Highlighter.
    2. Usage_Frequency: Tiene un orden claro: Weekly, Occasional , daily.
    3. Product_Size: Tiene una relación de tamaño: 250ml > 100ml > 30ml.
    4. Packaging_Type: No posee un orden implicto, pero puede ser jerarquico en funcionalidad o tamaño.
- **Nominales (Sin orden implicito):**
    1. Brand: Nombre de marcas, sin relacion de orden.
    2. Gender_Target: No tiene orden, no se puede decir que uno es mayor que otro y son independientes no existe una relacion que los conecte.
    3. Main_Ingredient: No tiene jerarquía ni dependencia.
    4. Product_Name: Representan los nombre o identificador
    5. Country_of_Origing: Etiqueta geográfica

In [51]:
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany

Agregar columnas al DF para realizar las transformaciones

##### **Transformacion de columnas categoricas ORDINALES**

##### *Transformacion - Definiendo Orden con un mapeo de las categorías*

In [52]:
# Label Encoding - Maintaining order
# Category: Usage_Frequency
# Order: From lowest to highest frequency

df['Usage_Frequency'].unique()

array(['Weekly', 'Occasional', 'Daily', 'Monthly'], dtype=object)

In [53]:
# Dictionary with the order
order = {'Monthly':0,'Occasional':1, 'Weekly':2, 'Daily':3}
# Apply map
df['Usage_Frequency_encoded'] = df['Usage_Frequency'].map(order)
df[['Usage_Frequency', 'Usage_Frequency_encoded']].head()

  Usage_Frequency  Usage_Frequency_encoded
0          Weekly                        2
1      Occasional                        1
2           Daily                        3
3      Occasional                        1
4      Occasional                        1

In [54]:
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin,Usage_Frequency_encoded
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia,2
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK,1
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy,3
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea,1
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany,1

###### Columna Category

In [55]:
df['Category'].unique()

array(['Blush', 'Makeup Remover', 'Highlighter', 'Face Mask',
       'Foundation', 'Powder', 'Lip Gloss', 'CC Cream', 'Eye Shadow',
       'Concealer', 'Eyeliner', 'Lipstick', 'Setting Spray', 'Cleanser',
       'Bronzer', 'Primer', 'Face Oil', 'Contour', 'Mascara', 'Serum',
       'BB Cream', 'Exfoliator', 'Lip Liner', 'Moisturizer'], dtype=object)

Orden en secuencia de uso:

Makeup Remover → Cleanser → Exfoliator → Face Mask → Face Oil → Serum → Moisturizer → Primer → CC Cream → BB Cream → Foundation → Concealer → Contour → Blush → Highlighter → Bronzer → Eye Shadow → Eyeliner → Mascara → Lip Liner → Lipstick → Lip Gloss → Powder → Setting Spray

In [56]:
#Dictionary
order_category = {'Makeup Remover':0, 'Cleanser':1, 'Exfoliator':2, 'Face Mask':3, 'Face Oil':4,'Serum':5,'Moisturizer':6, 'Primer':7, 'CC Cream': 8, 'BB Cream':9,
                 'Foundation':10, 'Concealer':11, 'Contour':12, 'Blush':13, 'Highlighter':14, 'Bronzer':15, 'Eye Shadow':16, 'Eyeliner':17, 'Mascara':18, 'Lip Liner':19,
                 'Lipstick':20, 'Lip Gloss':21, 'Powder':22, 'Setting Spray':23 }
# Apply map
df['Category_encoded'] = df['Category'].map(order_category)
df[['Category', 'Category_encoded']].head()

         Category  Category_encoded
0           Blush                13
1  Makeup Remover                 0
2     Highlighter                14
3       Face Mask                 3
4     Highlighter                14

##### *Transformacion - Importando libreria preprocessing de sklearn*

In [57]:
from sklearn.preprocessing import LabelEncoder

# Object LabelEncoder
pack_label_encoder = LabelEncoder()

# Encoding
df['Packaging_Type_encoded'] = pack_label_encoder.fit_transform(df['Packaging_Type'])

df[['Packaging_Type','Packaging_Type_encoded']].head()

  Packaging_Type  Packaging_Type_encoded
0           Tube                       5
1         Bottle                       0
2        Compact                       1
3           Tube                       5
4        Compact                       1

##### **Transformacion de columnas categoricas NOMINALES**

In [58]:
# One-Hot Encoding
brand_encoded = pd.get_dummies(df['Brand'], prefix='Brand')
gender_encoded = pd.get_dummies(df['Gender_Target'], prefix='Gender_Target')
df_new = pd.concat([df,brand_encoded, gender_encoded], axis=1)
df_new.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,...,Brand_Shiseido,Brand_Sisley,Brand_Tarte,Brand_Tatcha,Brand_Too Faced,Brand_Urban Decay,Brand_Yves Saint Laurent,Gender_Target_Female,Gender_Target_Male,Gender_Target_Unisex
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,...,False,False,False,False,False,False,False,True,False,False
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,...,False,False,False,False,False,False,False,False,False,True
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,...,False,False,False,False,False,False,False,False,True,False
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,...,False,False,False,False,False,False,False,False,True,False
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,...,False,False,False,False,False,False,False,True,False,False

##### Columna Main_Ingredient

In [59]:
main_ing_encoded = pd.get_dummies(df['Main_Ingredient'], prefix='Main_Ingredient')
df_new_main = pd.concat([df,main_ing_encoded], axis=1)
df_new_main.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,...,Usage_Frequency_encoded,Category_encoded,Packaging_Type_encoded,Main_Ingredient_Aloe Vera,Main_Ingredient_Glycerin,Main_Ingredient_Hyaluronic Acid,Main_Ingredient_Retinol,Main_Ingredient_Salicylic Acid,Main_Ingredient_Shea Butter,Main_Ingredient_Vitamin C
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,...,2,13,5,False,False,False,True,False,False,False
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,...,1,0,0,False,False,False,False,False,True,False
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,...,3,14,1,True,False,False,False,False,False,False
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,...,1,3,5,False,True,False,False,False,False,False
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,...,1,14,1,False,True,False,False,False,False,False

In [60]:
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin,Usage_Frequency_encoded,Category_encoded,Packaging_Type_encoded
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia,2,13,5
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK,1,0,0
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy,3,14,1
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea,1,3,5
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany,1,14,1

In [61]:
gender_encoded.head()

   Gender_Target_Female  Gender_Target_Male  Gender_Target_Unisex
0                  True               False                 False
1                 False               False                  True
2                 False                True                 False
3                 False                True                 False
4                  True               False                 False

In [62]:
# Add gender_encoded to df origin
df = pd.concat([df, gender_encoded,main_ing_encoded], axis=1)
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,...,Gender_Target_Female,Gender_Target_Male,Gender_Target_Unisex,Main_Ingredient_Aloe Vera,Main_Ingredient_Glycerin,Main_Ingredient_Hyaluronic Acid,Main_Ingredient_Retinol,Main_Ingredient_Salicylic Acid,Main_Ingredient_Shea Butter,Main_Ingredient_Vitamin C
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,...,True,False,False,False,False,False,True,False,False,False
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,...,False,False,True,False,False,False,False,False,True,False
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,...,False,True,False,True,False,False,False,False,False,False
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,...,False,True,False,False,True,False,False,False,False,False
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,...,True,False,False,False,True,False,False,False,False,False

#### Normalización

In [63]:
df.head()

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,...,Gender_Target_Female,Gender_Target_Male,Gender_Target_Unisex,Main_Ingredient_Aloe Vera,Main_Ingredient_Glycerin,Main_Ingredient_Hyaluronic Acid,Main_Ingredient_Retinol,Main_Ingredient_Salicylic Acid,Main_Ingredient_Shea Butter,Main_Ingredient_Vitamin C
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,...,True,False,False,False,False,False,True,False,False,False
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,...,False,False,True,False,False,False,False,False,True,False
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,...,False,True,False,True,False,False,False,False,False,False
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,...,False,True,False,False,True,False,False,False,False,False
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,...,True,False,False,False,True,False,False,False,False,False

##### *Extración de informacion*
A la serie Product_Size, se le extraera el texto 'ml'.

In [101]:
# Remove 'ml'
df['Product_Size_NoML'] = df['Product_Size'].str.extract(r'(\d+)ml', expand=False)
# Convert type from object to float
df['Product_Size_NoML'] = df['Product_Size_NoML'].astype(float)
df['Product_Size_NoML'].dtype

dtype('float64')

In [99]:
df['Product_Size_NoML'].describe()

count    15000.000000
mean       129.233333
std         78.544405
min         30.000000
25%         50.000000
50%        100.000000
75%        200.000000
max        250.000000
Name: Product_Size_NoML, dtype: float64

##### *Eliminación de espacios extras*

In [109]:
# Delete space at the beginning, end and between
df.head()
for s in df.select_dtypes(include=['object']):
    df[s] = df[s].str.strip()
    df[s] = df[s].str.replace(r'\s+', ' ', regex=True)